# Generated by Django 6.0 on 2026-01-04 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment_courseprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='estimated_hours',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='course',
            name='preview_video_url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_lectures',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='total_duration',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='watched_duration',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='last_accessed_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='watched_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.video'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional YouTube/Vimeo link'),
        ),
    ]
