# Generated by Django 6.0 on 2026-01-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='created_at',
        ),
    ]
